# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-05 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7)),
                ('series_of_pass', models.CharField(max_length=2)),
                ('number_of_pass', models.CharField(max_length=7)),
                ('issued_by_pass', models.TextField(max_length=200)),
                ('date_of_pass', models.DateField()),
                ('ident_number', models.CharField(max_length=14)),
                ('place_of_birth', models.TextField(max_length=200)),
                ('place_of_living', models.CharField(choices=[('Минск', 'Минск'), ('Гомель', 'Гомель'), ('Гродно', 'Гродно'), ('Витебск', 'Витебск'), ('Брест', 'Брест')], max_length=7)),
                ('adress', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('town', models.CharField(choices=[('Минск', 'Минск'), ('Гомель', 'Гомель'), ('Гродно', 'Гродно'), ('Витебск', 'Витебск'), ('Брест', 'Брест')], max_length=7)),
                ('place_of_registry', models.TextField(max_length=200)),
                ('marital', models.CharField(choices=[('Женат/Замужем', 'Женат/Замужем'), ('Холост/Не замужем', 'Холост/Не замужем'), ('Вдовец/Вдова', 'Вдовец/Вдова')], max_length=19)),
                ('citizenship', models.CharField(choices=[('Республика Беларусь', 'Республика Беларусь'), ('Российская Федерация', 'Российская Федерация'), ('Другое', 'Другое')], max_length=20)),
                ('disability', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3)),
                ('retiree', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3)),
                ('liable', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3)),
            ],
        ),
    ]
