# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import econapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0004_auto_20191104_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=econapp.models.image_folder),
        ),
    ]
