# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-06 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0006_auto_20200507_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passw',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
