# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-07 07:21
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0008_auto_20200507_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='e_mail',
        ),
    ]
