# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-02 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='born',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
