# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0010_auto_20200507_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='userame',
        ),
        migrations.RemoveField(
            model_name='person',
            name='login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passw',
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='userame',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='econapp.User'),
            preserve_default=False,
        ),
    ]
