# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-03 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0011_auto_20191203_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_total',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
