# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-03 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0013_auto_20191203_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_title',
        ),
    ]
