# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-03 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0015_auto_20191203_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_title',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
