# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-03 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0018_auto_20191203_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
