# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-03 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0022_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
