# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-03 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econapp', '0023_auto_20191204_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
    ]
